INSERT INTO categories (category_name)
VALUES ('Appetizers'),
        ('Rice Dishes'),
        ('Vegetarian'),
        ('Pan-fried Noodles'),
        ('Noodles with Soup'),
        ('Chef Recommended');

INSERT INTO items (item_name, item_desc, item_price, category_id)
VALUES ('Hot Basil Stir Fried with Crispy Egg',
        'Ground pork, Fresh Garlic, Thai hot basil, Sweet Pepper,
Crispy Egg and Served over steamed rice',
        15.95,
        6),
        ('Crab Fried Rice',
        'Fried rice with crab, onion, peas&carrot, cilantro and eggs',
        15.95,
        6),
        ('Satay Noodle',
        'Curried choice of protein*, wide noodle, mixed veggies
and eggs serve with peanut sauce',
        15.95,
        6),
        ('Nam Fried Rice',
        'Fried rice with Nam (Thai style sour sausage), Chinese
broccoli, fresh ginger, peanut and cilantro',
        15.95,
        6),

        ('Crispy Fried Green Beans',
        'Deep fried green beans, serve with Hot Mayo',
        6.95,
        1),
        ('Spring Rolls',
        'Deep fried spring rolls, serve with Thai sweet chili sauce',
        6.95,
        1),
        ('Fried Tofu',
        'Deep fried Tofu, serve with Thai sweet chili sauce',
        6.95,
        1),
        ('Shrimp Tempura',
        'Deep fried tempura shrimp, serve with Thai sweet chili sauce',
        7.95,
        1),
        ('Pot Sticker',
        'Deep fried pot stickers, serve with Thai sweet chili sauce',
        6.95,
        1),
        ('Crispy Fried Shrimp',
        'Deep fried golden shrimp, serve with Thai sweet chili sauce',
        7.95,
        1),


        ('House Fried Rice',
        'Thai homestyle fried rice with choice of protein*,
Chinese broccoli, onion, and tomato',
        13.95,
        2),
        ('Pineapple Fried Rice',
        'Thai fried rice with choice of protein*, pineapple, raisin, carrot,
onion, tomato and eggs',
        13.95,
        2),
        ('Thai Hot Basil Fried Rice',
        'Stir-fried choice of protein* with hot basil leaves, garlic and
sweet pepper',
        13.95,
        2),
        
        
        ('Sizzling Veggies over Rice',
        'Thai style sizzling veggies, stir-fry with soy sauce, serve on rice',
        13.95,
        3),
        ('Veggie Noodle Soup',
        'Noodles serve with vegetables and Tofu in
Thai-style mushroom soup',
        13.95,
        3),

        ('Pad Thai',
        'Stir-fried rice noodle with choice of protein*, eggs, bean
sprout, and chives with peanuts on side',
        13.95,
        4),
        ('Pad See Eew',
        'Stir-fried wide noodle with choice of protein*, eggs, Chinese
broccoli and sweet black sauce',
        13.95,
        4),
        ('Rad Nah',
        'Choice of noodle** with choice of protein* served in pork
base gravy sauce',
        13.95,
        4),
        ('Kua Gai',
        'Stir-fried wide noodle with choice of protein*, eggs, garlic, bean
sprout, onion, cilantro, lettuce and Thai-style sauce',
        13.95,
        4),
        ('Hot Basil Noodle',
        'Stir-fried wide noodle with choice of protein*, Thai hot basil,
carrot, tomato, garlic, sweet pepper',
        13.95,
        4),
        ('Pad Kee Mao',
        'Stir-fried wide noodle with choice of protein*, bamboo shoot,
onion, mixed veggies, sweet basil, eggs, and wine sauce',
        13.95,
        4),

        ('House Noodle Soup',
        'Noodle serve with self-made pork balls Chinese broccoli,
bean sprout, scallion and cilantro in NoodleHut special broth',
        10.95,
        5),
        ('Pork Meat Balls Noodle Soup',
        'Noodle serve with self made meat balls, Chinese broccoli,
bean sprout, scallion and cilantro in pork broth',
        10.95,
        5),
        ('Chicken Noodle Soup',
        'Noodle serve with chicken, bean sprout, lettuce, celery,
scallion, and cilantro inThai style chicken broth',
        9.95,
        5),
        ('Old Fashion Tom-Yum Noodle Soup',
        'Noodle with grounded pork, fish balls, bean sprout, green onion,
cilantro, ground peanut with Thai traditional Tom-Yum soup',
        10.95,
        5),
        ('Egg Noodle Soup',
        'Egg noodle serve with BBQ pork, fish ball, bean sprout,
green onion, cilantro',
        9.95,
        5);




