INSERT INTO categories (category_name)
VALUES ('Appetizers'),
        ('Rice Dishes'),
        ('Vegetarian'),
        ('Pan-fried Noodles'),
        ('Noodles with Soup'),
        ('Chef Recommended');

INSERT INTO items (item_name, item_desc, item_price, category)
VALUES ('Hot Basil Stir Fried with Crispy Egg',
        'Ground pork, Fresh Garlic, Thai hot basil, Sweet Pepper,
Crispy Egg and Served over steamed rice',
        15.95,
        'Chef Recommended'),
        ('Crab Fried Rice',
        'Fried rice with crab, onion, peas&carrot, cilantro and eggs',
        15.95,
        'Chef Recommended'),
        ('Satay Noodle',
        'Curried choice of protein*, wide noodle, mixed veggies
and eggs serve with peanut sauce',
        15.95,
        'Chef Recommended'),
        ('Nam Fried Rice',
        'Fried rice with Nam (Thai style sour sausage), Chinese
broccoli, fresh ginger, peanut and cilantro',
        15.95,
        'Chef Recommended'),

        ('Crispy Fried Green Beans',
        'Deep fried green beans, serve with Hot Mayo',
        6.95,
        'Appetizers'),
        ('Spring Rolls',
        'Deep fried spring rolls, serve with Thai sweet chili sauce',
        6.95,
        'Appetizers'),
        ('Fried Tofu',
        'Deep fried Tofu, serve with Thai sweet chili sauce',
        6.95,
        'Appetizers'),
        ('Shrimp Tempura',
        'Deep fried tempura shrimp, serve with Thai sweet chili sauce',
        7.95,
        'Appetizers'),
        ('Pot Sticker',
        'Deep fried pot stickers, serve with Thai sweet chili sauce',
        6.95,
        'Appetizers'),
        ('Crispy Fried Shrimp',
        'Deep fried golden shrimp, serve with Thai sweet chili sauce',
        7.95,
        'Appetizers'),
        ('Pad Woon Sen',
        'Stir-fried glass noodle with fresh tofu and mixed vegetables',
        13.95,
        'Vegetarian'),
        ('Sizzling Veggies over Rice',
        'Thai style sizzling veggies, stir-fry with soy sauce, serve on rice',
        13.95,
        'Vegetarian'),
        ('Veggie Noodle Soup',
        'Noodles serve with vegetables and Tofu in
Thai-style mushroom soup',
        13.95,
        'Vegetarian'),

        ('Pad Thai',
        'Stir-fried rice noodle with choice of protein*, eggs, bean
sprout, and chives with peanuts on side',
        13.95,
        'Pan-fried Noodles'),
        ('Pad See Eew',
        'Stir-fried wide noodle with choice of protein*, eggs, Chinese
broccoli and sweet black sauce',
        13.95,
        'Pan-fried Noodles'),
        ('Rad Nah',
        'Choice of noodle** with choice of protein* served in pork
base gravy sauce',
        13.95,
        'Pan-fried Noodles'),
        ('Kua Gai',
        'Stir-fried wide noodle with choice of protein*, eggs, garlic, bean
sprout, onion, cilantro, lettuce and Thai-style sauce',
        13.95,
        'Pan-fried Noodles'),
        ('Hot Basil Noodle',
        'Stir-fried wide noodle with choice of protein*, Thai hot basil,
carrot, tomato, garlic, sweet pepper',
        13.95,
        'Pan-fried Noodles'),
        ('Pad Kee Mao',
        'Stir-fried wide noodle with choice of protein*, bamboo shoot,
onion, mixed veggies, sweet basil, eggs, and wine sauce',
        13.95,
        'Pan-fried Noodles'),

        ('House Noodle Soup',
        'Noodle serve with self-made pork balls Chinese broccoli,
bean sprout, scallion and cilantro in NoodleHut special broth',
        10.95,
        'Noodles with Soup'),
        ('Pork Meat Balls Noodle Soup',
        'Noodle serve with self made meat balls, Chinese broccoli,
bean sprout, scallion and cilantro in pork broth',
        10.95,
        'Noodles with Soup'),
        ('Chicken Noodle Soup',
        'Noodle serve with chicken, bean sprout, lettuce, celery,
scallion, and cilantro inThai style chicken broth',
        9.95,
        'Noodles with Soup'),
        ('Old Fashion Tom-Yum Noodle Soup',
        'Noodle with grounded pork, fish balls, bean sprout, green onion,
cilantro, ground peanut with Thai traditional Tom-Yum soup',
        10.95,
        'Noodles with Soup'),
        ('Egg Noodle Soup',
        'Egg noodle serve with BBQ pork, fish ball, bean sprout,
green onion, cilantro',
        9.95,
        'Noodles with Soup');




